/*
 * This source file was generated by the Gradle 'init' task
 */
package labactivity;
import java.util.ArrayList;
import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         // We create a list of the INTERFACE type
        List<IPayable> accountsPayable = new ArrayList<>();
        List<IIdentifiable> accountIdentifier = new ArrayList<>();

        // Add unrelated objects to the same list
        accountsPayable.add(new SalariedEmployee("Alice Smith", "E001", 1200.00));
        accountsPayable.add(new Invoice("Widget-99", 5, 20.00));

        accountsPayable.add(new HourlyPaidEmployee("Bob Jones", "E002", 1500.00, 10.00));
        accountsPayable.add(new Invoice("Hammer-01", 2, 15.50));

        accountIdentifier.add(new DebitCards("Alan Walker", "4532881900234412"));

        System.out.println("Processing Payments:\n---------------------");

        for (IPayable item : accountsPayable) {
            // Polymorphism: Java knows which version of getPaymentAmount() to call!
            System.out.printf("Payment due: $%.2f%n", item.getPaymentAmount());
        }

        for (IIdentifiable entities : accountIdentifier){
            System.out.println("Type: " + entities.getClass().getSimpleName() + " | Global ID: " + entities.getUniqueIdentifier());
        }
        }
    }
 

